version: '3.7'
services:

  prod:
    build:
      target: prod
      context: ./
    image: bones-app_prod:${CI_COMMIT_SHORT_SHA:-latest}
    networks:
      - traefik-public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.port=80"
        - "traefik.docker.network=traefik-public"
        - "traefik.frontend.rule=Host:bones-app.${HOST:-docker.localhost}"
        - "traefik.tags=traefik-public"
        - "traefik.frontend.entryPoints=http,https"
        - "traefik.frontend.redirect.entryPoint=https"
      replicas: 1
      update_config:
        order: start-first
    restart: always 

networks:
  traefik-public:
    external: true
